version: '3'
services:
  elasticsearch:
    image: "elasticsearch:7.6.1"
    environment: 
      discovery.type: single-node
    ports: 
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
  # kibana:
  #   image: "docker.elastic.co/kibana/kibana:7.6.1"
  #   links:
  #     - "elasticsearch:elasticsearch"
  #   ports:
  #     - "5601:5601"
  #   restart: unless-stopped
  # cerebro: 
  #   image: "yannart/cerebro:latest"
  #   ports:
  #     - "9000:9000"
  #   restart: unless-stopped
  curl: 
    image: "ellerbrock/alpine-bash-curl-ssl"
    volumes:
      - "$PWD:/work"
    depends_on: 
      - "elasticsearch"
    command:
      - "sh"
      - "/work/public/wait-for-elastic.sh"
  api:
    build: .
    environment: 
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "8080:8080"
  