name: build our image

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $TAG
          docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag storeos/store-os-api:$TAG .